version: '3.9'

services:
  database:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin-password
      - MYSQL_USER=genreDbBoy
      - MYSQL_PASSWORD=genreDbBoy
      - MYSQL_DATABASE=genres
    volumes:
      - genres-database:/var/lib/data

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    command: ['redis-server', '/etc/redis/redis.conf']
    ports:
      - '6380:6379'
    volumes:
      - ./acl.conf:/etc/redis/users.acl
      - ./redis.conf:/etc/redis/redis.conf
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli', 'ping']
      interval: 10s
      retries: 5
      timeout: 5s
